version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: paws-wpp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - paws-network

  # Redis Commander for GUI management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: paws-wpp-redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin123
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - paws-network
    profiles:
      - dev

  # Azurite - Azure Storage Emulator
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: paws-wpp-azurite
    restart: unless-stopped
    ports:
      - "10000:10000" # Blob service
    volumes:
      - azurite_data:/data
    command: >
      azurite-blob
      --blobHost 0.0.0.0 --blobPort 10000
      --loose
      --location /data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "10000"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - paws-network

volumes:
  azurite_data:

networks:
  paws-network:
    driver: bridge